USE university;

DESCRIBE STUDENT;
DESCRIBE COURSE;
DESCRIBE ENROLL;

INSERT INTO STUDENT 
VALUES (600, '김명호', 4, '컴퓨터');

SELECT * 
FROM STUDENT;

DELETE FROM STUDENT
WHERE SNAME IS NULL;

CREATE TABLE TEMP_STUDENT
SELECT *
FROM STUDENT;

SELECT *
FROM TEMP_STUDENT;

INSERT INTO TEMP_STUDENT (SNO, SNAME, DEPT)
SELECT SNO, SNAME, DEPT
FROM STUDENT
WHERE DEPT='컴퓨터';

DELETE FROM TEMP_STUDENT
WHERE SYEAR IS NULL;

SET SQL_SAFE_UPDATES = 0;

update TEMP_STUDENT
set SYEAR = 2
where SNO = 300;

SELECT ALL DEPT, SYEAR
FROM TEMP_STUDENT;

SELECT CONCAT(SYEAR, '학년, ', SNAME) 정보
FROM TEMP_STUDENT;

-- 학과가 '컴퓨터'이고, 학년이 3학년인 학생의 학번과 이름 검색
-- STUDENT(SNO, SNAME, SYEAR, DEPT)
-- COURSE(CNO, CNAME, CREDIT, DEPT, PRNAME)
-- ENROLL(SNO*, CNO*, GRADE, MIDTERM, FINAL)

SELECT SNO, SNAME
FROM TEMP_STUDENT
WHERE DEPT = '컴퓨터' AND SYEAR = 4;

SELECT TIMESTAMP(NOW()) AS CurrentTimestamp;

ALTER TABLE TEMP_STUDENT
MODIFY SNO DOUBLE; 

INSERT INTO TEMP_STUDENT
VALUES (103.56123, '테스트', 3, '컴퓨터');

SELECT TRUNCATE(SNO, 2)
FROM TEMP_STUDENT;

SELECT SNO
FROM TEMP_STUDENT;

DELETE FROM TEMP_STUDENT
WHERE SNO BETWEEN 101 AND 104;

ALTER TABLE TEMP_STUDENT
ADD COLUMN BIRTH_DATE DATETIME;

INSERT INTO TEMP_STUDENT
VALUES (600, '홍길동', 1, '산공', '1998-04-07');

INSERT INTO TEMP_STUDENT (SNO, SNAME, SYEAR, BIRTH_DATE)
VALUES (700, '홍길동', 1, '1998-06-01');

SELECT SNAME 이름, TIMESTAMPDIFF(YEAR, BIRTH_DATE, DATE(NOW())) 나이
FROM TEMP_STUDENT
WHERE SNO = 600;

SELECT DATE_ADD('2000-01-01', INTERVAL '-1 5' MINUTE_SECOND) result;

SELECT *,
	CASE DEPT
	WHEN '컴퓨터' THEN '컴퓨터공학'
	WHEN '산공' THEN '산업공학'
	WHEN '전기' THEN '전기공학'
	ELSE '*****'
	END AS 학과
FROM TEMP_STUDENT;

SELECT *,
	CASE WHEN BIRTH_DATE IS NOT NULL THEN '정보 있음'
	ELSE '정보없음'
	END AS 생일
FROM TEMP_STUDENT;

SELECT SNAME, COALESCE(DEPT, '학과 정보 없음') 학과, COALESCE(BIRTH_DATE, '') 생일
FROM TEMP_STUDENT;

SELECT SNAME, DEPT, BIRTH_DATE,
	CASE WHEN DEPT IS NOT NULL THEN DEPT
		 ELSE (CASE WHEN BIRTH_DATE IS NOT NULL THEN BIRTH_DATE
			   ELSE '*****'
               END)
		 END 테스트
FROM TEMP_STUDENT;

INSERT INTO TEMP_STUDENT
VALUES (800, '김', NULL, NULL, '2000-01-01');

SELECT DEPT, COUNT(*) 인원수, COUNT(SYEAR) 학년대상, MAX(SYEAR) 최고학년, MIN(SYEAR) 최소학년, ROUND(AVG(SYEAR), 2) 평균학년FROM TEMP_STUDENT
GROUP BY DEPT;

SELECT DEPT, COUNT(*) 인원수, COUNT(SYEAR) 학년대상, MAX(SYEAR) 최고학년, MIN(SYEAR) 최소학년, ROUND(AVG(SYEAR), 2) 평균학년
FROM TEMP_STUDENT
GROUP BY DEPT HAVING AVG(SYEAR) > 1;




